// This file is automatically generated. Do not edit it directly.
// Stub file to prevent build errors - not currently in use

export const supabase = {
  auth: {
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    signInWithPassword: () => Promise.resolve({ data: null, error: new Error('Not implemented') }),
    signOut: () => Promise.resolve({ error: null })
  }
};